#############################################################################
# Makefile for building: XdatConverter.app/Contents/MacOS/XdatConverter
# Generated by qmake (3.0) (Qt 5.3.0)
# Project:  XdatConverter.pro
# Template: app
# Command: /Users/bidurbohara/Qt/5.3/clang_64/bin/qmake -spec macx-clang CONFIG+=x86_64 -o Makefile XdatConverter.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_QML_LIB -DQT_WIDGETS_LIB -DQT_CONCURRENT_LIB -DQT_NETWORK_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.6 -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.6 -Wall -W -fPIE $(DEFINES)
INCPATH       = -I../../../Qt/5.3/clang_64/mkspecs/macx-clang -I. -I/usr/local/hdf5/include -I../../../Qt/5.3/clang_64/lib/QtQuick.framework/Versions/5/Headers -I../../../Qt/5.3/clang_64/lib/QtQml.framework/Versions/5/Headers -I../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers -I../../../Qt/5.3/clang_64/lib/QtConcurrent.framework/Versions/5/Headers -I../../../Qt/5.3/clang_64/lib/QtNetwork.framework/Versions/5/Headers -I../../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers -I../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/AGL.framework/Headers -F/Users/bidurbohara/Qt/5.3/clang_64/lib
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.6
LIBS          = $(SUBLIBS) -F/Users/bidurbohara/Qt/5.3/clang_64/lib -L/Users/bidurbohara/Public/Qt_Examples/XdatConverter/../../../../../usr/local/hdf5/lib/ -lhdf5 -framework QtQuick -framework QtQml -framework QtNetwork -framework QtCore -framework QtGui -framework QtWidgets -framework QtConcurrent -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
QMAKE         = /Users/bidurbohara/Qt/5.3/clang_64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		converter.cpp \
		xdathdf.cpp \
		speciesinfo.cpp \
		atomicsystem.cpp qrc_qml.cpp \
		moc_converter.cpp \
		moc_speciesinfo.cpp \
		moc_atomicsystem.cpp
OBJECTS       = main.o \
		converter.o \
		xdathdf.o \
		speciesinfo.o \
		atomicsystem.o \
		qrc_qml.o \
		moc_converter.o \
		moc_speciesinfo.o \
		moc_atomicsystem.o
DIST          = ../../../Qt/5.3/clang_64/mkspecs/features/spec_pre.prf \
		../../../Qt/5.3/clang_64/mkspecs/qdevice.pri \
		../../../Qt/5.3/clang_64/mkspecs/features/device_config.prf \
		../../../Qt/5.3/clang_64/mkspecs/common/shell-unix.conf \
		../../../Qt/5.3/clang_64/mkspecs/common/unix.conf \
		../../../Qt/5.3/clang_64/mkspecs/common/mac.conf \
		../../../Qt/5.3/clang_64/mkspecs/common/macx.conf \
		../../../Qt/5.3/clang_64/mkspecs/common/gcc-base.conf \
		../../../Qt/5.3/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Qt/5.3/clang_64/mkspecs/common/clang.conf \
		../../../Qt/5.3/clang_64/mkspecs/common/clang-mac.conf \
		../../../Qt/5.3/clang_64/mkspecs/qconfig.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/features/qt_functions.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/qt_config.prf \
		../../../Qt/5.3/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Qt/5.3/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Qt/5.3/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/default_pre.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/mac/default_pre.prf \
		deployment.pri \
		../../../Qt/5.3/clang_64/mkspecs/features/resolve_config.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/default_post.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/warn_on.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/qt.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/resources.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/moc.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/uic.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/unix/thread.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/mac/rez.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/exceptions.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/yacc.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/lex.prf \
		XdatConverter.pro main.cpp \
		converter.cpp \
		xdathdf.cpp \
		speciesinfo.cpp \
		atomicsystem.cpp
QMAKE_TARGET  = XdatConverter
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = XdatConverter.app/Contents/MacOS/XdatConverter

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-O2 \
		-isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk \
		-mmacosx-version-min=10.6 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile XdatConverter.app/Contents/PkgInfo XdatConverter.app/Contents/Resources/empty.lproj XdatConverter.app/Contents/Info.plist $(TARGET)

$(TARGET): /Users/bidurbohara/Public/Qt_Examples/XdatConverter/../../../../../usr/local/hdf5/lib/libhdf5.a $(OBJECTS)  
	@test -d XdatConverter.app/Contents/MacOS/ || mkdir -p XdatConverter.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: XdatConverter.pro ../../../Qt/5.3/clang_64/mkspecs/macx-clang/qmake.conf ../../../Qt/5.3/clang_64/mkspecs/features/spec_pre.prf \
		../../../Qt/5.3/clang_64/mkspecs/qdevice.pri \
		../../../Qt/5.3/clang_64/mkspecs/features/device_config.prf \
		../../../Qt/5.3/clang_64/mkspecs/common/shell-unix.conf \
		../../../Qt/5.3/clang_64/mkspecs/common/unix.conf \
		../../../Qt/5.3/clang_64/mkspecs/common/mac.conf \
		../../../Qt/5.3/clang_64/mkspecs/common/macx.conf \
		../../../Qt/5.3/clang_64/mkspecs/common/gcc-base.conf \
		../../../Qt/5.3/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Qt/5.3/clang_64/mkspecs/common/clang.conf \
		../../../Qt/5.3/clang_64/mkspecs/common/clang-mac.conf \
		../../../Qt/5.3/clang_64/mkspecs/qconfig.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/features/qt_functions.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/qt_config.prf \
		../../../Qt/5.3/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Qt/5.3/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Qt/5.3/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/default_pre.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/mac/default_pre.prf \
		deployment.pri \
		../../../Qt/5.3/clang_64/mkspecs/features/resolve_config.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/default_post.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/warn_on.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/qt.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/resources.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/moc.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/uic.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/unix/thread.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/mac/rez.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/exceptions.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/yacc.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/lex.prf \
		XdatConverter.pro \
		qml.qrc \
		/Users/bidurbohara/Qt/5.3/clang_64/lib/QtQuick.framework/QtQuick.prl \
		/Users/bidurbohara/Qt/5.3/clang_64/lib/QtQml.framework/QtQml.prl \
		/Users/bidurbohara/Qt/5.3/clang_64/lib/QtNetwork.framework/QtNetwork.prl \
		/Users/bidurbohara/Qt/5.3/clang_64/lib/QtCore.framework/QtCore.prl \
		/Users/bidurbohara/Qt/5.3/clang_64/lib/QtGui.framework/QtGui.prl \
		/Users/bidurbohara/Qt/5.3/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/Users/bidurbohara/Qt/5.3/clang_64/lib/QtConcurrent.framework/QtConcurrent.prl
	$(QMAKE) -spec macx-clang CONFIG+=x86_64 -o Makefile XdatConverter.pro
../../../Qt/5.3/clang_64/mkspecs/features/spec_pre.prf:
../../../Qt/5.3/clang_64/mkspecs/qdevice.pri:
../../../Qt/5.3/clang_64/mkspecs/features/device_config.prf:
../../../Qt/5.3/clang_64/mkspecs/common/shell-unix.conf:
../../../Qt/5.3/clang_64/mkspecs/common/unix.conf:
../../../Qt/5.3/clang_64/mkspecs/common/mac.conf:
../../../Qt/5.3/clang_64/mkspecs/common/macx.conf:
../../../Qt/5.3/clang_64/mkspecs/common/gcc-base.conf:
../../../Qt/5.3/clang_64/mkspecs/common/gcc-base-mac.conf:
../../../Qt/5.3/clang_64/mkspecs/common/clang.conf:
../../../Qt/5.3/clang_64/mkspecs/common/clang-mac.conf:
../../../Qt/5.3/clang_64/mkspecs/qconfig.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_declarative.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_declarative_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_enginio.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_enginio_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_script.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkit.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkit_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../Qt/5.3/clang_64/mkspecs/features/qt_functions.prf:
../../../Qt/5.3/clang_64/mkspecs/features/qt_config.prf:
../../../Qt/5.3/clang_64/mkspecs/macx-clang/qmake.conf:
../../../Qt/5.3/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../Qt/5.3/clang_64/mkspecs/features/exclusive_builds.prf:
../../../Qt/5.3/clang_64/mkspecs/features/default_pre.prf:
../../../Qt/5.3/clang_64/mkspecs/features/mac/default_pre.prf:
deployment.pri:
../../../Qt/5.3/clang_64/mkspecs/features/resolve_config.prf:
../../../Qt/5.3/clang_64/mkspecs/features/default_post.prf:
../../../Qt/5.3/clang_64/mkspecs/features/mac/sdk.prf:
../../../Qt/5.3/clang_64/mkspecs/features/mac/default_post.prf:
../../../Qt/5.3/clang_64/mkspecs/features/mac/objective_c.prf:
../../../Qt/5.3/clang_64/mkspecs/features/warn_on.prf:
../../../Qt/5.3/clang_64/mkspecs/features/qt.prf:
../../../Qt/5.3/clang_64/mkspecs/features/resources.prf:
../../../Qt/5.3/clang_64/mkspecs/features/moc.prf:
../../../Qt/5.3/clang_64/mkspecs/features/unix/opengl.prf:
../../../Qt/5.3/clang_64/mkspecs/features/uic.prf:
../../../Qt/5.3/clang_64/mkspecs/features/unix/thread.prf:
../../../Qt/5.3/clang_64/mkspecs/features/mac/rez.prf:
../../../Qt/5.3/clang_64/mkspecs/features/testcase_targets.prf:
../../../Qt/5.3/clang_64/mkspecs/features/exceptions.prf:
../../../Qt/5.3/clang_64/mkspecs/features/yacc.prf:
../../../Qt/5.3/clang_64/mkspecs/features/lex.prf:
XdatConverter.pro:
qml.qrc:
/Users/bidurbohara/Qt/5.3/clang_64/lib/QtQuick.framework/QtQuick.prl:
/Users/bidurbohara/Qt/5.3/clang_64/lib/QtQml.framework/QtQml.prl:
/Users/bidurbohara/Qt/5.3/clang_64/lib/QtNetwork.framework/QtNetwork.prl:
/Users/bidurbohara/Qt/5.3/clang_64/lib/QtCore.framework/QtCore.prl:
/Users/bidurbohara/Qt/5.3/clang_64/lib/QtGui.framework/QtGui.prl:
/Users/bidurbohara/Qt/5.3/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/Users/bidurbohara/Qt/5.3/clang_64/lib/QtConcurrent.framework/QtConcurrent.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=x86_64 -o Makefile XdatConverter.pro

qmake_all: FORCE

XdatConverter.app/Contents/PkgInfo: 
	@test -d XdatConverter.app/Contents || mkdir -p XdatConverter.app/Contents
	@$(DEL_FILE) XdatConverter.app/Contents/PkgInfo
	@echo "APPL????" >XdatConverter.app/Contents/PkgInfo
XdatConverter.app/Contents/Resources/empty.lproj: 
	@test -d XdatConverter.app/Contents/Resources || mkdir -p XdatConverter.app/Contents/Resources
	@touch XdatConverter.app/Contents/Resources/empty.lproj
	
XdatConverter.app/Contents/Info.plist: 
	@test -d XdatConverter.app/Contents || mkdir -p XdatConverter.app/Contents
	@$(DEL_FILE) XdatConverter.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@ICON@,,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.XdatConverter,g" -e "s,@EXECUTABLE@,XdatConverter,g" -e "s,@TYPEINFO@,????,g" ../../../Qt/5.3/clang_64/mkspecs/macx-clang/Info.plist.app >XdatConverter.app/Contents/Info.plist
dist: 
	@test -d .tmp/XdatConverter1.0.0 || mkdir -p .tmp/XdatConverter1.0.0
	$(COPY_FILE) --parents $(DIST) .tmp/XdatConverter1.0.0/ && $(COPY_FILE) --parents qml.qrc .tmp/XdatConverter1.0.0/ && $(COPY_FILE) --parents converter.h xdathdf.h speciesinfo.h atomicsystem.h .tmp/XdatConverter1.0.0/ && $(COPY_FILE) --parents main.cpp converter.cpp xdathdf.cpp speciesinfo.cpp atomicsystem.cpp .tmp/XdatConverter1.0.0/ && (cd `dirname .tmp/XdatConverter1.0.0` && $(TAR) XdatConverter1.0.0.tar XdatConverter1.0.0 && $(COMPRESS) XdatConverter1.0.0.tar) && $(MOVE) `dirname .tmp/XdatConverter1.0.0`/XdatConverter1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/XdatConverter1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r XdatConverter.app
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all: qrc_qml.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qml.cpp
qrc_qml.cpp: qml.qrc \
		main.qml
	/Users/bidurbohara/Qt/5.3/clang_64/bin/rcc -name qml qml.qrc -o qrc_qml.cpp

compiler_moc_header_make_all: moc_converter.cpp moc_speciesinfo.cpp moc_atomicsystem.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_converter.cpp moc_speciesinfo.cpp moc_atomicsystem.cpp
moc_converter.cpp: ../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QFile \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QList \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qlist.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QTextStream \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qtextstream.h \
		../../../Qt/5.3/clang_64/lib/QtQml.framework/Versions/5/Headers/QQmlListProperty \
		../../../Qt/5.3/clang_64/lib/QtQml.framework/Versions/5/Headers/qqmllist.h \
		../../../Qt/5.3/clang_64/lib/QtConcurrent.framework/Versions/5/Headers/QtConcurrent \
		../../../Qt/5.3/clang_64/lib/QtConcurrent.framework/Versions/5/Headers/qtconcurrentcompilertest.h \
		../../../Qt/5.3/clang_64/lib/QtConcurrent.framework/Versions/5/Headers/qtconcurrentexception.h \
		../../../Qt/5.3/clang_64/lib/QtConcurrent.framework/Versions/5/Headers/qtconcurrentfilter.h \
		../../../Qt/5.3/clang_64/lib/QtConcurrent.framework/Versions/5/Headers/qtconcurrentfilterkernel.h \
		../../../Qt/5.3/clang_64/lib/QtConcurrent.framework/Versions/5/Headers/qtconcurrentfunctionwrappers.h \
		../../../Qt/5.3/clang_64/lib/QtConcurrent.framework/Versions/5/Headers/qtconcurrentiteratekernel.h \
		../../../Qt/5.3/clang_64/lib/QtConcurrent.framework/Versions/5/Headers/qtconcurrentmap.h \
		../../../Qt/5.3/clang_64/lib/QtConcurrent.framework/Versions/5/Headers/qtconcurrentmapkernel.h \
		../../../Qt/5.3/clang_64/lib/QtConcurrent.framework/Versions/5/Headers/qtconcurrentmedian.h \
		../../../Qt/5.3/clang_64/lib/QtConcurrent.framework/Versions/5/Headers/qtconcurrentreducekernel.h \
		../../../Qt/5.3/clang_64/lib/QtConcurrent.framework/Versions/5/Headers/qtconcurrentrun.h \
		../../../Qt/5.3/clang_64/lib/QtConcurrent.framework/Versions/5/Headers/qtconcurrentrunbase.h \
		../../../Qt/5.3/clang_64/lib/QtConcurrent.framework/Versions/5/Headers/qtconcurrentstoredfunctioncall.h \
		../../../Qt/5.3/clang_64/lib/QtConcurrent.framework/Versions/5/Headers/qtconcurrentthreadengine.h \
		../../../Qt/5.3/clang_64/lib/QtConcurrent.framework/Versions/5/Headers/qtconcurrentversion.h \
		speciesinfo.h \
		atomicsystem.h \
		converter.h
	/Users/bidurbohara/Qt/5.3/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/bidurbohara/Qt/5.3/clang_64/mkspecs/macx-clang -I/Users/bidurbohara/Public/Qt_Examples/XdatConverter -I/usr/local/hdf5/include -I/Users/bidurbohara/Qt/5.3/clang_64/lib/QtQuick.framework/Headers -I/Users/bidurbohara/Qt/5.3/clang_64/lib/QtQml.framework/Headers -I/Users/bidurbohara/Qt/5.3/clang_64/lib/QtWidgets.framework/Headers -I/Users/bidurbohara/Qt/5.3/clang_64/lib/QtConcurrent.framework/Headers -I/Users/bidurbohara/Qt/5.3/clang_64/lib/QtNetwork.framework/Headers -I/Users/bidurbohara/Qt/5.3/clang_64/lib/QtGui.framework/Headers -I/Users/bidurbohara/Qt/5.3/clang_64/lib/QtCore.framework/Headers -F/Users/bidurbohara/Qt/5.3/clang_64/lib converter.h -o moc_converter.cpp

moc_speciesinfo.cpp: ../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QFile \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QList \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qlist.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QTextStream \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qtextstream.h \
		../../../Qt/5.3/clang_64/lib/QtQml.framework/Versions/5/Headers/QQmlListProperty \
		../../../Qt/5.3/clang_64/lib/QtQml.framework/Versions/5/Headers/qqmllist.h \
		speciesinfo.h
	/Users/bidurbohara/Qt/5.3/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/bidurbohara/Qt/5.3/clang_64/mkspecs/macx-clang -I/Users/bidurbohara/Public/Qt_Examples/XdatConverter -I/usr/local/hdf5/include -I/Users/bidurbohara/Qt/5.3/clang_64/lib/QtQuick.framework/Headers -I/Users/bidurbohara/Qt/5.3/clang_64/lib/QtQml.framework/Headers -I/Users/bidurbohara/Qt/5.3/clang_64/lib/QtWidgets.framework/Headers -I/Users/bidurbohara/Qt/5.3/clang_64/lib/QtConcurrent.framework/Headers -I/Users/bidurbohara/Qt/5.3/clang_64/lib/QtNetwork.framework/Headers -I/Users/bidurbohara/Qt/5.3/clang_64/lib/QtGui.framework/Headers -I/Users/bidurbohara/Qt/5.3/clang_64/lib/QtCore.framework/Headers -F/Users/bidurbohara/Qt/5.3/clang_64/lib speciesinfo.h -o moc_speciesinfo.cpp

moc_atomicsystem.cpp: ../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QFile \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QList \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qlist.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QTextStream \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qtextstream.h \
		../../../Qt/5.3/clang_64/lib/QtQml.framework/Versions/5/Headers/QQmlListProperty \
		../../../Qt/5.3/clang_64/lib/QtQml.framework/Versions/5/Headers/qqmllist.h \
		atomicsystem.h
	/Users/bidurbohara/Qt/5.3/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/bidurbohara/Qt/5.3/clang_64/mkspecs/macx-clang -I/Users/bidurbohara/Public/Qt_Examples/XdatConverter -I/usr/local/hdf5/include -I/Users/bidurbohara/Qt/5.3/clang_64/lib/QtQuick.framework/Headers -I/Users/bidurbohara/Qt/5.3/clang_64/lib/QtQml.framework/Headers -I/Users/bidurbohara/Qt/5.3/clang_64/lib/QtWidgets.framework/Headers -I/Users/bidurbohara/Qt/5.3/clang_64/lib/QtConcurrent.framework/Headers -I/Users/bidurbohara/Qt/5.3/clang_64/lib/QtNetwork.framework/Headers -I/Users/bidurbohara/Qt/5.3/clang_64/lib/QtGui.framework/Headers -I/Users/bidurbohara/Qt/5.3/clang_64/lib/QtCore.framework/Headers -F/Users/bidurbohara/Qt/5.3/clang_64/lib atomicsystem.h -o moc_atomicsystem.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp ../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QApplication \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qapplication.h \
		../../../Qt/5.3/clang_64/lib/QtQml.framework/Versions/5/Headers/QQmlApplicationEngine \
		../../../Qt/5.3/clang_64/lib/QtQml.framework/Versions/5/Headers/qqmlapplicationengine.h \
		../../../Qt/5.3/clang_64/lib/QtQuick.framework/Versions/5/Headers/QtQuick \
		../../../Qt/5.3/clang_64/lib/QtQuick.framework/Versions/5/Headers/qtquickglobal.h \
		../../../Qt/5.3/clang_64/lib/QtQuick.framework/Versions/5/Headers/designersupport.h \
		../../../Qt/5.3/clang_64/lib/QtQuick.framework/Versions/5/Headers/qquickframebufferobject.h \
		../../../Qt/5.3/clang_64/lib/QtQuick.framework/Versions/5/Headers/qquickitem.h \
		../../../Qt/5.3/clang_64/lib/QtQuick.framework/Versions/5/Headers/qquickpainteditem.h \
		../../../Qt/5.3/clang_64/lib/QtQuick.framework/Versions/5/Headers/qquicktextdocument.h \
		../../../Qt/5.3/clang_64/lib/QtQuick.framework/Versions/5/Headers/qquickview.h \
		../../../Qt/5.3/clang_64/lib/QtQuick.framework/Versions/5/Headers/qquickwindow.h \
		../../../Qt/5.3/clang_64/lib/QtQuick.framework/Versions/5/Headers/qquickimageprovider.h \
		../../../Qt/5.3/clang_64/lib/QtQuick.framework/Versions/5/Headers/qsggeometry.h \
		../../../Qt/5.3/clang_64/lib/QtQuick.framework/Versions/5/Headers/qsgmaterial.h \
		../../../Qt/5.3/clang_64/lib/QtQuick.framework/Versions/5/Headers/qsgnode.h \
		../../../Qt/5.3/clang_64/lib/QtQuick.framework/Versions/5/Headers/qsgflatcolormaterial.h \
		../../../Qt/5.3/clang_64/lib/QtQuick.framework/Versions/5/Headers/qsgsimplematerial.h \
		../../../Qt/5.3/clang_64/lib/QtQuick.framework/Versions/5/Headers/qsgsimplerectnode.h \
		../../../Qt/5.3/clang_64/lib/QtQuick.framework/Versions/5/Headers/qsgsimpletexturenode.h \
		../../../Qt/5.3/clang_64/lib/QtQuick.framework/Versions/5/Headers/qsgtexture.h \
		../../../Qt/5.3/clang_64/lib/QtQuick.framework/Versions/5/Headers/qsgtexturematerial.h \
		../../../Qt/5.3/clang_64/lib/QtQuick.framework/Versions/5/Headers/qsgtextureprovider.h \
		../../../Qt/5.3/clang_64/lib/QtQuick.framework/Versions/5/Headers/qsgvertexcolormaterial.h \
		../../../Qt/5.3/clang_64/lib/QtQuick.framework/Versions/5/Headers/qtquickversion.h \
		converter.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QFile \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QList \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qlist.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QTextStream \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qtextstream.h \
		../../../Qt/5.3/clang_64/lib/QtQml.framework/Versions/5/Headers/QQmlListProperty \
		../../../Qt/5.3/clang_64/lib/QtQml.framework/Versions/5/Headers/qqmllist.h \
		../../../Qt/5.3/clang_64/lib/QtConcurrent.framework/Versions/5/Headers/QtConcurrent \
		../../../Qt/5.3/clang_64/lib/QtConcurrent.framework/Versions/5/Headers/qtconcurrentcompilertest.h \
		../../../Qt/5.3/clang_64/lib/QtConcurrent.framework/Versions/5/Headers/qtconcurrentexception.h \
		../../../Qt/5.3/clang_64/lib/QtConcurrent.framework/Versions/5/Headers/qtconcurrentfilter.h \
		../../../Qt/5.3/clang_64/lib/QtConcurrent.framework/Versions/5/Headers/qtconcurrentfilterkernel.h \
		../../../Qt/5.3/clang_64/lib/QtConcurrent.framework/Versions/5/Headers/qtconcurrentfunctionwrappers.h \
		../../../Qt/5.3/clang_64/lib/QtConcurrent.framework/Versions/5/Headers/qtconcurrentiteratekernel.h \
		../../../Qt/5.3/clang_64/lib/QtConcurrent.framework/Versions/5/Headers/qtconcurrentmap.h \
		../../../Qt/5.3/clang_64/lib/QtConcurrent.framework/Versions/5/Headers/qtconcurrentmapkernel.h \
		../../../Qt/5.3/clang_64/lib/QtConcurrent.framework/Versions/5/Headers/qtconcurrentmedian.h \
		../../../Qt/5.3/clang_64/lib/QtConcurrent.framework/Versions/5/Headers/qtconcurrentreducekernel.h \
		../../../Qt/5.3/clang_64/lib/QtConcurrent.framework/Versions/5/Headers/qtconcurrentrun.h \
		../../../Qt/5.3/clang_64/lib/QtConcurrent.framework/Versions/5/Headers/qtconcurrentrunbase.h \
		../../../Qt/5.3/clang_64/lib/QtConcurrent.framework/Versions/5/Headers/qtconcurrentstoredfunctioncall.h \
		../../../Qt/5.3/clang_64/lib/QtConcurrent.framework/Versions/5/Headers/qtconcurrentthreadengine.h \
		../../../Qt/5.3/clang_64/lib/QtConcurrent.framework/Versions/5/Headers/qtconcurrentversion.h \
		speciesinfo.h \
		atomicsystem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

converter.o: converter.cpp ../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QDebug \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QUrl \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qurl.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QFileInfo \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qfileinfo.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qmath.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qglobal.h \
		converter.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QFile \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QList \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qlist.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QTextStream \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qtextstream.h \
		../../../Qt/5.3/clang_64/lib/QtQml.framework/Versions/5/Headers/QQmlListProperty \
		../../../Qt/5.3/clang_64/lib/QtQml.framework/Versions/5/Headers/qqmllist.h \
		../../../Qt/5.3/clang_64/lib/QtConcurrent.framework/Versions/5/Headers/QtConcurrent \
		../../../Qt/5.3/clang_64/lib/QtConcurrent.framework/Versions/5/Headers/qtconcurrentcompilertest.h \
		../../../Qt/5.3/clang_64/lib/QtConcurrent.framework/Versions/5/Headers/qtconcurrentexception.h \
		../../../Qt/5.3/clang_64/lib/QtConcurrent.framework/Versions/5/Headers/qtconcurrentfilter.h \
		../../../Qt/5.3/clang_64/lib/QtConcurrent.framework/Versions/5/Headers/qtconcurrentfilterkernel.h \
		../../../Qt/5.3/clang_64/lib/QtConcurrent.framework/Versions/5/Headers/qtconcurrentfunctionwrappers.h \
		../../../Qt/5.3/clang_64/lib/QtConcurrent.framework/Versions/5/Headers/qtconcurrentiteratekernel.h \
		../../../Qt/5.3/clang_64/lib/QtConcurrent.framework/Versions/5/Headers/qtconcurrentmap.h \
		../../../Qt/5.3/clang_64/lib/QtConcurrent.framework/Versions/5/Headers/qtconcurrentmapkernel.h \
		../../../Qt/5.3/clang_64/lib/QtConcurrent.framework/Versions/5/Headers/qtconcurrentmedian.h \
		../../../Qt/5.3/clang_64/lib/QtConcurrent.framework/Versions/5/Headers/qtconcurrentreducekernel.h \
		../../../Qt/5.3/clang_64/lib/QtConcurrent.framework/Versions/5/Headers/qtconcurrentrun.h \
		../../../Qt/5.3/clang_64/lib/QtConcurrent.framework/Versions/5/Headers/qtconcurrentrunbase.h \
		../../../Qt/5.3/clang_64/lib/QtConcurrent.framework/Versions/5/Headers/qtconcurrentstoredfunctioncall.h \
		../../../Qt/5.3/clang_64/lib/QtConcurrent.framework/Versions/5/Headers/qtconcurrentthreadengine.h \
		../../../Qt/5.3/clang_64/lib/QtConcurrent.framework/Versions/5/Headers/qtconcurrentversion.h \
		speciesinfo.h \
		atomicsystem.h \
		xdathdf.h \
		/usr/local/hdf5/include/hdf5.h \
		/usr/local/hdf5/include/H5public.h \
		/usr/local/hdf5/include/H5pubconf.h \
		/usr/local/hdf5/include/H5version.h \
		/usr/local/hdf5/include/H5api_adpt.h \
		/usr/local/hdf5/include/H5Apublic.h \
		/usr/local/hdf5/include/H5Ipublic.h \
		/usr/local/hdf5/include/H5Opublic.h \
		/usr/local/hdf5/include/H5Lpublic.h \
		/usr/local/hdf5/include/H5Tpublic.h \
		/usr/local/hdf5/include/H5ACpublic.h \
		/usr/local/hdf5/include/H5Cpublic.h \
		/usr/local/hdf5/include/H5Dpublic.h \
		/usr/local/hdf5/include/H5Epublic.h \
		/usr/local/hdf5/include/H5Epubgen.h \
		/usr/local/hdf5/include/H5Fpublic.h \
		/usr/local/hdf5/include/H5FDpublic.h \
		/usr/local/hdf5/include/H5Gpublic.h \
		/usr/local/hdf5/include/H5MMpublic.h \
		/usr/local/hdf5/include/H5Ppublic.h \
		/usr/local/hdf5/include/H5Zpublic.h \
		/usr/local/hdf5/include/H5Rpublic.h \
		/usr/local/hdf5/include/H5Spublic.h \
		/usr/local/hdf5/include/H5FDcore.h \
		/usr/local/hdf5/include/H5FDfamily.h \
		/usr/local/hdf5/include/H5FDlog.h \
		/usr/local/hdf5/include/H5FDmpi.h \
		/usr/local/hdf5/include/H5FDmpio.h \
		/usr/local/hdf5/include/H5FDmulti.h \
		/usr/local/hdf5/include/H5FDsec2.h \
		/usr/local/hdf5/include/H5FDstdio.h \
		/usr/local/hdf5/include/H5FDdirect.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o converter.o converter.cpp

xdathdf.o: xdathdf.cpp ../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QDebug \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h \
		xdathdf.h \
		/usr/local/hdf5/include/hdf5.h \
		/usr/local/hdf5/include/H5public.h \
		/usr/local/hdf5/include/H5pubconf.h \
		/usr/local/hdf5/include/H5version.h \
		/usr/local/hdf5/include/H5api_adpt.h \
		/usr/local/hdf5/include/H5Apublic.h \
		/usr/local/hdf5/include/H5Ipublic.h \
		/usr/local/hdf5/include/H5Opublic.h \
		/usr/local/hdf5/include/H5Lpublic.h \
		/usr/local/hdf5/include/H5Tpublic.h \
		/usr/local/hdf5/include/H5ACpublic.h \
		/usr/local/hdf5/include/H5Cpublic.h \
		/usr/local/hdf5/include/H5Dpublic.h \
		/usr/local/hdf5/include/H5Epublic.h \
		/usr/local/hdf5/include/H5Epubgen.h \
		/usr/local/hdf5/include/H5Fpublic.h \
		/usr/local/hdf5/include/H5FDpublic.h \
		/usr/local/hdf5/include/H5Gpublic.h \
		/usr/local/hdf5/include/H5MMpublic.h \
		/usr/local/hdf5/include/H5Ppublic.h \
		/usr/local/hdf5/include/H5Zpublic.h \
		/usr/local/hdf5/include/H5Rpublic.h \
		/usr/local/hdf5/include/H5Spublic.h \
		/usr/local/hdf5/include/H5FDcore.h \
		/usr/local/hdf5/include/H5FDfamily.h \
		/usr/local/hdf5/include/H5FDlog.h \
		/usr/local/hdf5/include/H5FDmpi.h \
		/usr/local/hdf5/include/H5FDmpio.h \
		/usr/local/hdf5/include/H5FDmulti.h \
		/usr/local/hdf5/include/H5FDsec2.h \
		/usr/local/hdf5/include/H5FDstdio.h \
		/usr/local/hdf5/include/H5FDdirect.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		atomicsystem.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QFile \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QList \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qlist.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QTextStream \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qtextstream.h \
		../../../Qt/5.3/clang_64/lib/QtQml.framework/Versions/5/Headers/QQmlListProperty \
		../../../Qt/5.3/clang_64/lib/QtQml.framework/Versions/5/Headers/qqmllist.h \
		speciesinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o xdathdf.o xdathdf.cpp

speciesinfo.o: speciesinfo.cpp speciesinfo.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QFile \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QList \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qlist.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QTextStream \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qtextstream.h \
		../../../Qt/5.3/clang_64/lib/QtQml.framework/Versions/5/Headers/QQmlListProperty \
		../../../Qt/5.3/clang_64/lib/QtQml.framework/Versions/5/Headers/qqmllist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o speciesinfo.o speciesinfo.cpp

atomicsystem.o: atomicsystem.cpp atomicsystem.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QFile \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QList \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qlist.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QTextStream \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qtextstream.h \
		../../../Qt/5.3/clang_64/lib/QtQml.framework/Versions/5/Headers/QQmlListProperty \
		../../../Qt/5.3/clang_64/lib/QtQml.framework/Versions/5/Headers/qqmllist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o atomicsystem.o atomicsystem.cpp

qrc_qml.o: qrc_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qml.o qrc_qml.cpp

moc_converter.o: moc_converter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_converter.o moc_converter.cpp

moc_speciesinfo.o: moc_speciesinfo.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_speciesinfo.o moc_speciesinfo.cpp

moc_atomicsystem.o: moc_atomicsystem.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_atomicsystem.o moc_atomicsystem.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/XdatConverter/bin || mkdir -p $(INSTALL_ROOT)/opt/XdatConverter/bin
	$(DEL_FILE) -r "$(INSTALL_ROOT)/opt/XdatConverter/bin/XdatConverter.app"
	
	-$(INSTALL_DIR) "XdatConverter.app" "$(INSTALL_ROOT)/opt/XdatConverter/bin/XdatConverter.app"

uninstall_target: FORCE
	-$(DEL_FILE) -r "$(INSTALL_ROOT)/opt/XdatConverter/bin/XdatConverter.app"
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/XdatConverter/bin/ 


install:  install_target  FORCE

uninstall: uninstall_target   FORCE

FORCE:

